apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app: {{ .Release.Name }}
data:
  .env: |
{{ .Values.appConfig.content | indent 4 }}
  
  {{- if .Values.caCert }}
  {{- if .Values.caCert.enabled }}
  root-ca.crt: |
{{ .Values.caCert.content | indent 4 }}
  {{- end }}
  {{- end }}
